export const SERVER_ORG_ADDRESS = 'SERVER_ORG_ADDRESS';
export const SERVER_ORG_ADDRESS_NEW = 'SERVER_ORG_STAG_ADDRESS_NEW';
export const USING_API_ORG_NEW = 'USING_API_ORG_NEW';

export const SERVER_ADDRESS = 'http://localhost:3000';
export const API_URL_REMOTE_KEY = 'API_URL';
export const API_URL = '/api/v1';
// --
export const SERVER_ADDRESS_REMOTE_KEY = 'SERVER_ADDRESS_STAG';
export const DMS_SERVER_ADDRESS_REMOTE_KEY = 'DMS_SERVER_ADDRESS_STAG';
export const DMS_BELLE_HEALTH_SOURCE_KEY = 'DMS_BELLE_HEALTH_SOURCE';
export const CMS_SERVER_ADDRESS_REMOTE_KEY = 'CMS_SERVER_ADDRESS_STAG';
export const CMS_TOKEN = 'CMS_TOKEN_STAG';
export const IOS_APP_VERSION_REMOTE_KEY = 'IOS_APP_VERSION_STAG';
export const ANDROID_APP_VERSION_REMOTE_KEY = 'ANDROID_APP_VERSION_STAG';
export const QUESTIONNAIRE_REMOTE_KEY = 'QUESTIONNAIRE_SERVER_URL_STAG';
// -- cognito
export const COGNITO_APP_CLIENT_ID_KEY = 'COGNITO_APP_CLIENT_ID_STAG';
export const COGNITO_SERVICE_CONFIGURATION_KEY =
    'COGNITO_SERVICE_CONFIGURATION_STAG';
export const COGNITO_USER_POOL_ID = 'COGNITO_POOL_ID_STAG';

export const MIRROR_PARAM = 'MINIAPP_MIRROR_PARAM_STAG';
export const MIRROR_PARAM_RE_DOWNLOAD = 'MINIAPP_MIRROR_PARAM_RE_DOWNLOAD_STAG';
export const STUDY_PARAM = 'MINIAPP_STUDY_PARAM_STAG';
export const STUDY_PARAM_RE_DOWNLOAD = 'MINIAPP_STUDY_PARAM_RE_DOWNLOAD_STAG';
export const DISEASE_FROM_KEY = 'DISEASE_FROM_STAG';
export const API_URL_V_REMOTE_KEY = 'API_URL_VERSION';
export const BTPM_SERVICE_URL = 'BTPM_API_STAG';
export const ADDRESS_SUPER_APP_REMOTE_KEY = 'ADDRESS_SUPER_APP_STAG';
export const OOPS_NUMBER_ONEK_KEY = 'OOPS_NUMBER_ONEK_STAG';
export const ORDER_SERVER_URL_KEY = 'ORDER_SERVER_URL';
export const PRODUCT_SERVER_URL_KEY = 'PRODUCT_SERVER_URL';
export const USER_SERVER_URL_KEY = 'USER_SERVER_URL';

export const GG_MAP_KEY_ANDROID = 'GG_MAP_KEY_ANDROID';
export const GG_MAP_KEY_IOS = 'GG_MAP_KEY_IOS';
export const SCANNER_SERVER_REMOTE_KEY = 'SCANNER_SERVER_URL';
export const FACE_3D_SERVER_REMOTE_KEY = 'FACE_3D_SERVER_URL';
export const FACE_3D_SERVER_PUBLIC_REMOTE_KEY = 'FACE_3D_SERVER_URL_PUBLIC';

export const SHARED_CASES_SERVER_URL_KEY = 'SHARED_CASES_SERVER_URL_STAG';

export const APPSFLYER_DEV_KEY = 'nwPNM6xhiNC7aPWoTeQQ87';
export const APP_IOD = '1629482674';

export const RECAPTCHA_KEY_ANDROID = 'RECAPTCHA_KEY_ANDROID';
export const RECAPTCHA_KEY_IOS = 'RECAPTCHA_KEY_IOS';

export const DMS_SERVER_ADDRESS = 'DMS_SERVER_ADDRESS_DEV';

export const USING_ACCELERATION = 'USING_ACCELERATION';

export const MARKET_SERVER_URL = 'MARKET_SERVER_URL'
export const ANALYTIC_STAG_URL = 'ANALYTIC_STAG_URL';
export const VIETNAM_USER = 'VIETNAM_USER';
